# Generated by Django 3.2.4 on 2021-06-04 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profileuploadmodel',
            name='user',
        ),
    ]
